name: binary_serializable
description: Efficient binary serialization and deserialization, optimized for streams of binary data.
version: 0.2.1

repository: https://github.com/abitofevrything/binary_serializable/tree/main/packages/binary_serializable

environment:
  sdk: ^3.5.0-243.0.dev

resolution: workspace

dependencies:
  meta: ^1.15.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
