name: binary_serializable
description: Efficient binary serialization and deserialization, optimized for streams of binary data.
version: 0.3.2

repository: https://github.com/abitofevrything/binary_serializable/tree/main/packages/binary_serializable

environment:
  sdk: ^3.5.0

resolution: workspace

dependencies:
  meta: ^1.16.0

dev_dependencies:
  benchmark_harness: ^2.2.2
  collection: ^1.19.0
  lints: ^4.0.0
  pretty_bytes: ^6.2.0
  test: ^1.25.8
