name: example
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  binary_serializable: ^0.2.0

dev_dependencies:
  binary_serializable_generator:
    path: ../binary_serializable_generator
  build_runner: ^2.4.11

dependency_overrides:
  binary_serializable:
    path: ../binary_serializable
