name: binary_serializable_generator
description: Code generation for binary_serializable's BinaryTypes.
version: 0.3.4

repository: https://github.com/abitofevrything/binary_serializable/tree/main/packages/binary_serializable_generator

environment:
  sdk: ^3.5.0

resolution: workspace

dependencies:
  source_gen: ^1.5.0
  binary_serializable: ^0.3.2
  analyzer: ^6.9.0
  build: ^2.4.1
  build_config: ^1.1.1
  code_builder: ^4.10.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
